version: '3.8'

services:
  webbase:
    image: webbase:prod
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
    depends_on:
      - mongodb-primary
    environment:
      - DATABASE_URL=mongodb://mongodb-primary:27017,mongodb-secondary:27017/webbase?replicaSet=rs0

  mongodb-primary:
    image: mongo:8
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
